trigger:
- master
variables:
  path: 'server_web_app'
  buildPath: 'server_web_app/'

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    cd $(path)
    npm install
    cd ..
  displayName: 'npm install'



- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(buildPath)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'dropserver'
    publishLocation: 'Container'
  displayName: 'publish artifact'
